### ISSUE TITLE
Please add dedot for Kubernetes labels: ERROR: Can't merge a non object mapping [kubernetes.labels.app] with an object mapping [kubernetes.labels.app]

### ISSUE THREAD

**Issue by imriss** [banzaicloud/logging-operator#118]
**Is your feature request related to a problem? Please describe.**
When there is "." on the labels, ES returns 400 with this error message:
```
ERROR: Can't merge a non object mapping [kubernetes.labels.app] with an object mapping [kubernetes.labels.app]
```

**Describe the solution you'd like**
There is a filter provided in [this issue](https://github.com/fluent/fluent-bit/issues/1134#issuecomment-489213375) that replaces the dots in the labels. Please add something similar to the configmaps.

**Describe alternatives you've considered**
[This PR](https://github.com/fluent/fluent-bit/pull/1279). However, it is seems that it is inactive (closed).

**Additional context**
N/A

**Comment by pepov** [comment]
Just to clarify: a label like `app: "foo.bar" ` is enough to trigger this issue?

**Comment by imriss** [comment]
I have to try that. The labels that trigger the issue are something like: `app.kubernetes.io/name: testapp`.

**Comment by imriss** [comment]
Labels like `app: "foo.bar"` did not trigger the issue.

**Comment by pepov** [comment]
I misunderstood as I beleive dots in the label keys (not in the values) cause the issue. I will try to reproduce and think about where we should fix it, as it's not necessarily fluentbit's concern since the output is configured in fluentd. I was thinking of adding support for the following plugin to pair it with elasticsearch: https://github.com/lunardial/fluent-plugin-dedot_filter

**Comment by pepov** [comment]
We are going to fix this, just need to prioritize over other issues. Can you workaround this issue or is this a blocker for you right now? I beleive this can temporarily be mitigated in elasticsearch as well: https://www.elastic.co/guide/en/logstash/current/plugins-filters-de_dot.html

Also pull requests are always welcome!

**Comment by imriss** [comment]
I will try the workaround for now. Thanks

**Comment by tirelibirefe** [comment]
Were you able to find a solution for this bug? Because the problem is still exists.

**Comment by tirelibirefe** [comment]
> We are going to fix this, just need to prioritize over other issues. Can you workaround this issue or is this a blocker for you right now? I beleive this can temporarily be mitigated in elasticsearch as well: https://www.elastic.co/guide/en/logstash/current/plugins-filters-de_dot.html
> 
> Also pull requests are always welcome!

it is not suitable to use helm charts.

**Comment by pepov** [comment]
we support the dedot filter already: https://banzaicloud.com/docs/one-eye/logging-operator/plugins/filters/dedot/

**Comment by dorroddorrod** [comment]
How can i apply the dedot only on the labels fields ? 
Currently,  even the `log.level` changed to `log-level` when adding the dedot

**Comment by pepov** [comment]
I would redirect this question to the plugin: https://github.com/lunardial/fluent-plugin-dedot_filter

**Comment by true64gurus** [comment]
@dorroddorrod  were you able to find resolution ? I am having same exact issue . I am using operator 3.13.
